"""Topology guards D1–D5 — AST-walking architecture ratchets (no imports of
the audited code; stdlib ast only).

Each rule collects (file, line, ...) sites and compares them against an
EMBEDDED explicit allowlist generated by scanning ETHER @208993a. A NEW site
fails the test with a clear message; sites disappearing is fine (shrink-only
ratchet — when a grandfathered site is removed, delete it from the list).
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Iterator, List, Optional, Set, Tuple

REPO = Path(__file__).resolve().parents[1]

_SKIP_DIRS = {".git", ".venv", "__pycache__", "node_modules", "memory"}


def _py_files(*roots: str) -> Iterator[Path]:
    for root in roots:
        for p in sorted((REPO / root).rglob("*.py")):
            if any(part in _SKIP_DIRS for part in p.parts):
                continue
            yield p


def _imports(path: Path) -> Iterator[Tuple[int, str, Optional[str]]]:
    """Yield (line, module, enclosing_function) for every import in path."""
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))

    def walk(node: ast.AST, fn: Optional[str]) -> Iterator[Tuple[int, str, Optional[str]]]:
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                yield from walk(child, child.name)
            elif isinstance(child, ast.Import):
                for a in child.names:
                    yield (child.lineno, a.name, fn)
            elif isinstance(child, ast.ImportFrom):
                mod = ("." * child.level) + (child.module or "")
                yield (child.lineno, mod, fn)
            else:
                yield from walk(child, fn)

    yield from walk(tree, None)


def _rel(p: Path) -> str:
    return p.relative_to(REPO).as_posix()


# ---------------------------------------------------------------------------
# D1: gems must not import core beyond the leaf contracts
# (core.schemas / core.vectors). Everything else is a layering inversion.
# ---------------------------------------------------------------------------

# grandfathered @208993a — shrink-only
D1_ALLOWLIST: Set[Tuple[str, int, str]] = frozenset(
    [
        ("gems/amethyst/evolution.py", 10, "core.learning"),
        ("gems/black_tourmaline/security.py", 18, "core.config"),
        ("gems/citrine/memory.py", 13, "core.chunking"),
        ("gems/clear_quartz/sandbox.py", 401, "core.assert_audit"),
        ("gems/clear_quartz/sandbox.py", 277, "core.pipeline_hooks"),
        ("gems/clear_quartz/sandbox.py", 147, "core.pipeline_hooks"),
        ("gems/clear_quartz/sandbox.py", 152, "core.test_synth"),
        ("gems/clear_quartz/sandbox.py", 158, "core.assert_harness"),
        ("gems/grandidierite/fabricate.py", 94, "core.registry"),
        ("gems/grandidierite/fabricate.py", 130, "core.registry"),
        ("gems/grandidierite/fabricate.py", 155, "core.registry"),
    ]
)

_D1_LEGAL = ("core.schemas", "core.vectors")


def test_d1_gems_do_not_import_core_beyond_leaf_contracts():
    sites = set()
    for p in _py_files("gems"):
        for line, mod, _fn in _imports(p):
            top = mod.lstrip(".").split(".")[0]
            if top != "core":
                continue
            if any(mod == ok or mod.startswith(ok + ".") for ok in _D1_LEGAL):
                continue
            sites.add((_rel(p), line, mod))
    new = sites - D1_ALLOWLIST
    assert not new, (
        "D1: NEW gems→core imports (layering inversion). Gems may only import "
        f"{_D1_LEGAL} from core; constructor-inject everything else:\n"
        + "\n".join(f"  {f}:{ln} imports {m}" for f, ln, m in sorted(new))
    )


# ---------------------------------------------------------------------------
# D2: core must not import gems (gems are plugins below core). Grandfathered
# bridges are listed; core/loop, core/spine and core/vectors are HARD ZERO
# except the single sanctioned lazy bridge in LoopRunner._default_run_tool.
# ---------------------------------------------------------------------------

# The ONE gems import allowed under core/loop (spec §3): a lazy function-local
# bridge so LoopRunner works without constructor injection in this stage.
D2_SANCTIONED_GEM_BRIDGE = (
    "core/loop/runner.py",
    "gems.grandidierite.registry",
    "_default_run_tool",
)

# grandfathered @208993a — shrink-only
D2_ALLOWLIST: Set[Tuple[str, int, str]] = frozenset(
    [
        ("core/health_check.py", 349, "gems.clear_quartz.sandbox"),
        ("core/holdout.py", 132, "gems.clear_quartz.sandbox"),
        ("core/pipeline.py", 228, "gems.grandidierite.registry"),
        ("core/pipeline.py", 270, "gems.grandidierite.registry"),
        ("core/pipeline.py", 330, "gems.grandidierite.registry"),
        ("core/pipeline.py", 653, "gems.grandidierite.registry"),
        # :940/:1010 at 208993a; shifted +26 by the stage-1 dispatcher branch.
        ("core/pipeline.py", 966, "gems.grandidierite.registry"),
        ("core/pipeline.py", 1034, "gems.grandidierite.registry"),
        ("core/registry.py", 41, "gems.clear_quartz.sandbox"),
        ("core/registry.py", 42, "gems.rose_quartz.router"),
        ("core/registry.py", 43, "gems.selenite.planner"),
        ("core/registry.py", 44, "gems.black_tourmaline.security"),
        ("core/registry.py", 45, "gems.labradorite.profiler"),
        ("core/registry.py", 46, "gems.amethyst.evolution"),
        ("core/registry.py", 47, "gems.grandidierite.extension"),
        ("core/registry.py", 58, "gems.citrine.memory"),
        ("core/tool_reconcile.py", 41, "gems.grandidierite.fabricate"),
        ("core/verifier.py", 649, "gems.clear_quartz.sandbox"),
    ]
)


def _is_gems(mod: str) -> bool:
    return mod == "gems" or mod.startswith("gems.")


def test_d2_core_does_not_import_gems():
    sites = set()
    for p in _py_files("core"):
        rel = _rel(p)
        for line, mod, _fn in _imports(p):
            if _is_gems(mod):
                sites.add((rel, line, mod))
    # The sanctioned bridge is exempt here (matched on file+module, not the
    # brittle line) and pinned to _default_run_tool by the hard-zero test.
    new = {
        s
        for s in sites - D2_ALLOWLIST
        if (s[0], s[2]) != (D2_SANCTIONED_GEM_BRIDGE[0], D2_SANCTIONED_GEM_BRIDGE[1])
    }
    assert not new, (
        "D2: NEW core→gems imports (layering inversion). Route through the "
        "registry / constructor injection instead:\n"
        + "\n".join(f"  {f}:{ln} imports {m}" for f, ln, m in sorted(new))
    )


def test_d2_hard_zero_new_layers():
    """core/loop/**, core/spine/**, core/vectors.py: ZERO gems imports, with the
    single exception of LoopRunner._default_run_tool (spec §3, D2 note)."""
    offenders: List[str] = []
    for p in list(_py_files("core/loop", "core/spine")) + [REPO / "core" / "vectors.py"]:
        rel = _rel(p)
        for line, mod, fn in _imports(p):
            if not _is_gems(mod):
                continue
            if (rel, mod, fn) == D2_SANCTIONED_GEM_BRIDGE:
                continue
            offenders.append(f"  {rel}:{line} imports {mod}")
    assert not offenders, (
        "D2 HARD RULE: core/loop, core/spine and core/vectors.py must have "
        "ZERO gems imports (gem access is constructor-injected; the only "
        "sanctioned bridge is LoopRunner._default_run_tool):\n" + "\n".join(offenders)
    )


# ---------------------------------------------------------------------------
# D3: single writer. (i) the Spine kernel stays clean; (ii) no NEW memory/
# state writers outside the grandfathered set (mirrors audit pack STATE-001).
# ---------------------------------------------------------------------------

# Blessed writer modules (the single-writer pattern itself).
_D3_WRITER_MODULES = {"core/batch_queue.py", "core/spine/state_io.py", "core/spine/__init__.py"}

_STATE_HINTS = (
    "memory",
    "MEMORY",
    "vault",
    "ledger",
    "failure_graph",
    "GRAPH_PATH",
    "STATE_PATH",
    "curriculum",
    "runs",
    "quiz",
    "VAULT",
    "LEDGER",
    "GRAPH",
    "STATE",
)

_WRITE_NAMES = ("write_text", "write_bytes", "json.dump", "dump")

# grandfathered @208993a — shrink-only (mirrors audit pack STATE-001 sites)
D3_ALLOWLIST: Set[Tuple[str, int]] = frozenset(
    [
        ("core/autonomy.py", 252),
        ("core/curriculum.py", 137),
        ("core/fail_streak.py", 26),
        ("core/failure_graph.py", 78),
        ("gems/rose_quartz/burst.py", 37),
        ("scripts/quiz.py", 144),
    ]
)


def _call_name(func: ast.AST) -> str:
    name = ""
    while isinstance(func, ast.Attribute):
        name = "." + func.attr + name
        func = func.value
    if isinstance(func, ast.Name):
        name = func.id + name
    return name


def _is_write_call(node: ast.Call) -> bool:
    fn = _call_name(node.func)
    if fn.endswith(_WRITE_NAMES):
        return True
    if fn.endswith("open") or fn == "open":
        for a in list(node.args[1:]) + [k.value for k in node.keywords if k.arg == "mode"]:
            if (
                isinstance(a, ast.Constant)
                and isinstance(a.value, str)
                and any(m in a.value for m in ("w", "a", "+"))
            ):
                return True
    if fn.endswith(".replace"):  # atomic rename target
        return True
    return False


def _targets_state(node: ast.Call) -> bool:
    dump = ast.dump(node)
    return any(h in dump for h in _STATE_HINTS)


def test_d3_spine_kernel_stays_clean():
    for rel in ("core/spine/state_io.py",):
        for line, mod, _fn in _imports(REPO / rel):
            assert not (mod == "core.pipeline" or mod.startswith("core.pipeline.")), (
                f"D3: {rel}:{line} imports {mod} — the Spine kernel must not "
                "depend on the pipeline god object"
            )
            assert not _is_gems(mod), (
                f"D3: {rel}:{line} imports {mod} — the Spine kernel must not " "depend on gems"
            )


def test_d3_no_new_state_writers():
    sites = set()
    for p in _py_files("cli", "core", "dashboard", "gems", "scripts", "tools"):
        rel = _rel(p)
        if rel in _D3_WRITER_MODULES:
            continue
        tree = ast.parse(p.read_text(encoding="utf-8"), filename=rel)
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and _is_write_call(node) and _targets_state(node):
                sites.add((rel, node.lineno))
    new = sites - D3_ALLOWLIST
    assert not new, (
        "D3: NEW memory/ state writers outside the single-writer allowlist. "
        "Route the write through core/spine/state_io.py (rmw / write_json / "
        "append_jsonl):\n" + "\n".join(f"  {f}:{ln}" for f, ln in sorted(new))
    )


# ---------------------------------------------------------------------------
# D4: dashboard reads memory/ only via dashboard/collector.py.
# ---------------------------------------------------------------------------

# grandfathered @208993a — shrink-only
D4_ALLOWLIST: Set[Tuple[str, int]] = frozenset(
    [
        ("dashboard/live_feed.py", 48),
        ("dashboard/live_feed.py", 61),
        ("dashboard/live_feed.py", 143),
    ]
)

_D4_READ_NAMES = ("open", "read_text", "read_bytes", "glob", "rglob", "_read_json")
_D4_MEM_MARKERS = ('"memory', "'memory", "memory/")


def test_d4_dashboard_reads_via_collector_only():
    sites = set()
    for p in _py_files("dashboard"):
        rel = _rel(p)
        if rel == "dashboard/collector.py":
            continue
        tree = ast.parse(p.read_text(encoding="utf-8"), filename=rel)
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            fn = _call_name(node.func)
            if not (fn.endswith(_D4_READ_NAMES) or fn == "open"):
                continue
            hay = ast.dump(node)
            if any(m in hay for m in _D4_MEM_MARKERS):
                sites.add((rel, node.lineno))
    new = sites - D4_ALLOWLIST
    assert not new, (
        "D4: NEW direct memory/ reads in dashboard/ outside "
        "dashboard/collector.py — dashboard panels read through the collector "
        "API:\n" + "\n".join(f"  {f}:{ln}" for f, ln in sorted(new))
    )


# ---------------------------------------------------------------------------
# D5: entry points must not import the pipeline god object.
# ---------------------------------------------------------------------------

# grandfathered @208993a — shrink-only (flywheel drives Pipeline directly in
# its worker path; the quarantine move is a later roadmap stage)
D5_ALLOWLIST: Set[Tuple[str, int]] = frozenset(
    [
        ("scripts/flywheel.py", 122),
    ]
)


def test_d5_entry_points_do_not_import_pipeline():
    sites = set()
    for rel in ("scripts/flywheel.py", "dashboard/app.py"):
        for line, mod, _fn in _imports(REPO / rel):
            if mod == "core.pipeline" or mod.startswith("core.pipeline."):
                sites.add((rel, line))
    new = sites - D5_ALLOWLIST
    assert not new, (
        "D5: NEW core.pipeline imports in entry points — entries must reach "
        "the loop via the runner, not the god object:\n"
        + "\n".join(f"  {f}:{ln}" for f, ln in sorted(new))
    )


# ---------------------------------------------------------------------------
# New modules import cleanly and expose the spec'd API.
# ---------------------------------------------------------------------------


def test_new_modules_importable(monkeypatch):
    import core.vectors as vectors
    import core.spine.state_io as state_io
    import core.loop.runner as runner
    import core.loop.handlers.finalize as finalize
    from core.loop import loop_runner_enabled

    for name in ("VertexID", "Provenance", "Vector", "prompt_hash"):
        assert hasattr(vectors, name), f"core.vectors missing {name}"
    for name in ("state_lock", "read_json", "write_json", "rmw", "append_jsonl"):
        assert hasattr(state_io, name), f"core.spine.state_io missing {name}"
    assert hasattr(runner, "LoopRunner")
    for name in ("FinalizeContext", "FinalizeOutcome", "FinalizeHandler"):
        assert hasattr(finalize, name), f"core.loop.handlers.finalize missing {name}"
    monkeypatch.delenv("ETHER_LOOP_RUNNER", raising=False)
    assert loop_runner_enabled() is False
    monkeypatch.setenv("ETHER_LOOP_RUNNER", "1")
    assert loop_runner_enabled() is True
