"""Day-3 pins: PR CI workflow shape, dataset policy, budget sync, pack placement.

These tests fail if the audit-gates workflow loses its DAG/matrix/warn-mode
shape, if eval data sneaks back into the git index, if the fetch script stops
reproducing the canonical dataset, or if the two budget registers drift apart.
SPEC: Phase 4 / Day-3 §4.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
WORKFLOW = ROOT / ".github" / "workflows" / "audit-gates.yml"


def _git(*args: str) -> str:
    proc = subprocess.run(
        ["git", "-C", str(ROOT), *args],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert proc.returncode == 0, f"git {' '.join(args)} failed: {proc.stderr}"
    return proc.stdout


# 1. Workflow sanity ---------------------------------------------------------


def test_audit_gates_workflow_shape():
    text = WORKFLOW.read_text(encoding="utf-8")
    doc = yaml.safe_load(text)
    assert isinstance(doc, dict), "workflow must parse as a mapping"

    jobs = doc.get("jobs") or {}
    assert {"lint", "audit-rules", "contracts", "pytest", "gate"} <= set(
        jobs
    ), f"DAG jobs missing: have {sorted(jobs)}"

    # S-08: every action reference is pinned to a full 40-char commit SHA.
    uses = re.findall(r"uses:\s*(\S+)", text)
    assert uses, "no uses: references found — wrong file?"
    unpinned = [u for u in uses if not re.fullmatch(r"\S+@[0-9a-f]{40}", u)]
    assert not unpinned, f"actions not SHA-pinned: {unpinned}"

    # pytest job: 2x2 matrix (python x ETHER_LOOP_RUNNER) + shadow selftest step.
    pytest_job = jobs["pytest"]
    matrix = (pytest_job.get("strategy") or {}).get("matrix") or {}
    assert matrix.get("python") == ["3.11", "3.12"], matrix
    assert matrix.get("loop_runner") == ["0", "1"], matrix
    assert (pytest_job.get("env") or {}).get("ETHER_LOOP_RUNNER") == "${{ matrix.loop_runner }}"
    steps_text = "\n".join(str(s.get("run", "")) for s in pytest_job.get("steps") or [])
    assert "shadow_runner.py --selftest" in steps_text, steps_text
    assert "--timeout" not in steps_text, "pytest-timeout is not a dependency"

    # ruff steps are warn-mode (pre-existing F401/format drift at 819bc92; the
    # audit engine is the blocking gate until burn-down — ADR 0004 residual).
    lint_steps = jobs["lint"].get("steps") or []
    ruff_steps = [s for s in lint_steps if str(s.get("run", "")).startswith("pipx run ruff")]
    assert len(ruff_steps) == 2, f"expected ruff check + format steps, got {len(ruff_steps)}"
    for step in ruff_steps:
        assert step.get("continue-on-error") is True, step


# 2. Dataset policy ----------------------------------------------------------


def test_eval_data_is_untracked():
    if not (ROOT / ".git").exists():
        pytest.skip("git-index assertions need a checkout, not an archive copy")
    tracked = _git("ls-files", "memory/").splitlines()
    leaked = [
        p for p in tracked if p.startswith("memory/quizzes/") or p.startswith("memory/datasets/")
    ]
    assert not leaked, f"eval data back in the index: {leaked}"
    # Deliberate exception (ADR 0004): the seeded smoke queue stays tracked.
    assert "memory/batch_queue.json" in tracked, tracked
    # memory/ stays gitignored so untracked copies stay untracked.
    ignored = _git("check-ignore", "memory/quizzes", "memory/datasets").splitlines()
    assert "memory/quizzes" in ignored and "memory/datasets" in ignored, ignored


# 3. Fetch script ------------------------------------------------------------


def test_fetch_datasets_check_and_write(tmp_path):
    script = ROOT / "scripts" / "fetch_datasets.py"
    # --check: in a checkout the file is present and canonical -> exit 0;
    # in a fresh clone (archive) it is legitimately absent -> exit 1.
    target = ROOT / "memory" / "datasets" / "mbpp_lite.json"
    expected = 0 if target.exists() else 1
    proc = subprocess.run(
        [sys.executable, str(script), "--check"],
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert proc.returncode == expected, (proc.stdout, proc.stderr)

    # Write mode against a tmp copy: regenerated bytes == the embedded canonical.
    from scripts import fetch_datasets

    target = tmp_path / "memory" / "datasets" / "mbpp_lite.json"
    fetch_datasets.write_dataset(target)
    assert target.read_text(encoding="utf-8") == fetch_datasets.CANONICAL
    assert fetch_datasets.check_dataset(target) is True
    target.write_text('{"drifted": true}\n', encoding="utf-8")
    assert fetch_datasets.check_dataset(target) is False


# 4. Budget sync -------------------------------------------------------------


def test_budgets_are_in_sync():
    config = yaml.safe_load((ROOT / "config" / "audit-rules.yaml").read_text(encoding="utf-8"))
    baseline = json.loads((ROOT / "tools" / "audit" / "findings_baseline.json").read_text("utf-8"))
    cfg_budgets = config.get("budgets") or {}
    base_budgets = baseline.get("budgets") or {}
    # Day-3 ratchets: pipeline_run_lines 790 -> 710 (may-only-lower),
    # env_getenv_sites 188 -> 191 (post-Day-2 reality, ADRs 0001/0002).
    assert cfg_budgets["pipeline_run_lines"] == 710
    assert base_budgets["pipeline_run_lines"] == 710
    assert cfg_budgets["env_getenv_sites"] == 191
    assert base_budgets["env_getenv_sites"] == 191
    for key in ("pipeline_run_lines", "env_getenv_sites"):
        assert cfg_budgets[key] == base_budgets[key], f"budget drift on {key}"


# 5. Pack placement ----------------------------------------------------------


@pytest.mark.parametrize(
    "rel",
    [
        "tools/audit/audit_runner.py",
        "config/audit-rules.yaml",
        "tests/test_audit_contracts.py",
        "dashboard/static/audit_panel.html",
        ".pre-commit-config.yaml",
    ],
)
def test_pack_files_exist(rel):
    assert (ROOT / rel).is_file(), f"audit-pack file missing: {rel}"
