# Install Desktop shortcut with HARDCODED absolute path to the @ETHER repo.
# Safe when Desktop lives under OneDrive. ASCII-only for PowerShell 5.x.

$ErrorActionPreference = "Stop"

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Runtime = Join-Path $Root "scripts\desktop_runtime.py"
$RepoBat = Join-Path $Root "scripts\ETHER.bat"
$PyProject = Join-Path $Root "pyproject.toml"

if (-not (Test-Path $Runtime)) {
    Write-Error "Not found: $Runtime"
}
if (-not (Test-Path $RepoBat)) {
    Write-Error "Not found: $RepoBat"
}
if (-not (Test-Path $PyProject)) {
    Write-Error "Not found: $PyProject - wrong root? $Root"
}

$Desktop = [Environment]::GetFolderPath("Desktop")
$DesktopBat = Join-Path $Desktop "ETHER.bat"
$LnkPath = Join-Path $Desktop "ETHER Control Matrix.lnk"

# Desktop wrapper with absolute paths (no relative %~dp0 tricks)
$line1 = "@echo off"
$line2 = "setlocal"
$line3 = "REM Auto-generated by install_desktop_shortcut.ps1"
$line4 = "set ETHER_ROOT=$Root"
$line5 = "cd /d ""$Root"""
$line6 = "if not exist ""$Root\scripts\desktop_runtime.py"" ("
$line7 = "  echo [ERROR] Repo missing at $Root"
$line8 = "  pause"
$line9 = "  exit /b 1"
$line10 = ")"
$line11 = "call ""$RepoBat"""

$wrapper = @(...
    $line1,
    $line2,
    $line3,
    $line4,
    $line5,
    $line6,
    $line7,
    $line8,
    $line9,
    $line10,
    $line11
) -join "`r`n"

# Fix: PowerShell does not use @(... with ellipsis - build array properly
$wrapperLines = @(
    $line1,
    $line2,
    $line3,
    $line4,
    $line5,
    $line6,
    $line7,
    $line8,
    $line9,
    $line10,
    $line11
)
Set-Content -Path $DesktopBat -Value $wrapperLines -Encoding ASCII

$Wsh = New-Object -ComObject WScript.Shell
$Sc = $Wsh.CreateShortcut($LnkPath)
$Sc.TargetPath = $DesktopBat
$Sc.WorkingDirectory = $Root
$Sc.WindowStyle = 1
$Sc.Description = "ETHER dashboard and flywheel - repo $Root"
$Sc.Save()

Write-Host ""
Write-Host "OK - Desktop launcher installed" -ForegroundColor Green
Write-Host "  Repo root : $Root"
Write-Host "  Wrapper   : $DesktopBat"
Write-Host "  Shortcut  : $LnkPath"
Write-Host ""
Write-Host "Wrapper contents:"
Get-Content $DesktopBat | ForEach-Object { Write-Host "  $_" }
Write-Host ""
Write-Host "Double-click 'ETHER Control Matrix' on the Desktop."
