# Install Desktop shortcut with HARDCODED absolute path to the @ETHER repo.
# Safe when Desktop lives under OneDrive. ASCII-only for PowerShell 5.x.

$ErrorActionPreference = "Stop"

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Runtime = Join-Path $Root "scripts\desktop_runtime.py"
$RepoBat = Join-Path $Root "scripts\ETHER.bat"
$PyProject = Join-Path $Root "pyproject.toml"

if (-not (Test-Path $Runtime)) {
    Write-Error "Not found: $Runtime"
}
if (-not (Test-Path $RepoBat)) {
    Write-Error "Not found: $RepoBat"
}
if (-not (Test-Path $PyProject)) {
    Write-Error "Not found: $PyProject - wrong root? $Root"
}

$Desktop = [Environment]::GetFolderPath("Desktop")
$DesktopBat = Join-Path $Desktop "ETHER.bat"
$LnkPath = Join-Path $Desktop "ETHER Control Matrix.lnk"

$wrapperLines = @(
    "@echo off"
    "setlocal"
    "REM Auto-generated by install_desktop_shortcut.ps1"
    "set ETHER_ROOT=$Root"
    "cd /d ""$Root"""
    "if not exist ""$Root\scripts\desktop_runtime.py"" ("
    "  echo [ERROR] Repo missing at $Root"
    "  pause"
    "  exit /b 1"
    ")"
    "call ""$RepoBat"""
)
Set-Content -Path $DesktopBat -Value $wrapperLines -Encoding ASCII

$Wsh = New-Object -ComObject WScript.Shell
$Sc = $Wsh.CreateShortcut($LnkPath)
$Sc.TargetPath = $DesktopBat
$Sc.WorkingDirectory = $Root
$Sc.WindowStyle = 1
$Sc.Description = "ETHER dashboard and flywheel - repo $Root"
$Sc.Save()

Write-Host ""
Write-Host "OK - Desktop launcher installed" -ForegroundColor Green
Write-Host "  Repo root : $Root"
Write-Host "  Wrapper   : $DesktopBat"
Write-Host "  Shortcut  : $LnkPath"
Write-Host ""
Write-Host "Wrapper contents:"
Get-Content $DesktopBat | ForEach-Object { Write-Host "  $_" }
Write-Host ""
Write-Host "Double-click 'ETHER Control Matrix' on the Desktop."
