"""Grandidierite — controlled tool generation + quarantine write."""

from __future__ import annotations

import re
from pathlib import Path
from datetime import datetime, timezone

from core.schemas import (
    Envelope,
    ResponseEnvelope,
    GemError,
    GemErrorType,
    GrandidieriteRequest,
    GrandidieriteResponse,
)


def _sanitize_name(name: str) -> str:
    name = re.sub(r"[^0-9a-zA-Z_]", "_", name.strip()) or "new_tool"
    if name[0].isdigit():
        name = f"tool_{name}"
    return name[:64]


class Grandidierite:
    TEMPLATES = {
        "basic_python_tool": '''def {name}({args}):
    """{docstring}"""
    raise NotImplementedError("Generated by Grandidierite — implement me")
'''
    }

    def __init__(self, quarantine_dir: Path | None = None):
        self.quarantine_dir = quarantine_dir or Path("tools/quarantine")
        self.quarantine_dir.mkdir(parents=True, exist_ok=True)

    def execute(self, request: Envelope) -> ResponseEnvelope:
        try:
            if isinstance(request.payload, GrandidieriteRequest):
                tool_req = request.payload.tool_request
                template_id = request.payload.template_id
            else:
                data = request.payload.model_dump() if hasattr(request.payload, "model_dump") else {}
                tool_req = data.get("tool_request", {})
                template_id = data.get("template_id", "basic_python_tool")

            name = _sanitize_name(str(tool_req.get("name", "new_tool")))
            args = tool_req.get("args", "")
            docstring = tool_req.get("docstring", "Auto-generated tool")
            template = self.TEMPLATES.get(template_id, self.TEMPLATES["basic_python_tool"])
            code = template.format(name=name, args=args, docstring=docstring)

            ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            out = self.quarantine_dir / f"{name}_{ts}.py"
            out.write_text(code, encoding="utf-8")

            return ResponseEnvelope(
                task_id=request.task_id,
                source_gem="grandidierite",
                payload=GrandidieriteResponse(
                    generated_code=code,
                    template_used=template_id,
                    validation_status="pending",
                ),
            )
        except Exception as e:
            return ResponseEnvelope(
                task_id=request.task_id,
                source_gem="grandidierite",
                error=GemError(type=GemErrorType.RUNTIME, message=str(e), recoverable=True),
            )
