"""Grandidierite — tool generation, fabrication pipeline, registry run/list."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

from core.schemas import (
    Envelope,
    ResponseEnvelope,
    GemError,
    GemErrorType,
    GrandidieriteRequest,
    GrandidieriteResponse,
)
from gems.grandidierite.registry import list_tools, run_tool
from gems.grandidierite.fabricate import fabricate


def _sanitize_name(name: str) -> str:
    name = re.sub(r"[^0-9a-zA-Z_]", "_", name.strip()) or "new_tool"
    if name[0].isdigit():
        name = f"tool_{name}"
    return name[:64]


class Grandidierite:
    TEMPLATES = {
        "basic_python_tool": '''#!/usr/bin/env python3
"""{docstring}"""
from __future__ import annotations
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _lib import emit, read_input

def {name}({args}):
    """{docstring}"""
    raise NotImplementedError("Generated by Grandidierite — implement me")

def main() -> None:
    inp = read_input()
    emit(False, error="not implemented", input=inp)

if __name__ == "__main__":
    main()
'''
    }

    def __init__(self, quarantine_dir: Path | None = None):
        self.quarantine_dir = quarantine_dir or Path("tools/quarantine")
        self.quarantine_dir.mkdir(parents=True, exist_ok=True)
        Path("tools/persistent").mkdir(parents=True, exist_ok=True)

    def execute(self, request: Envelope) -> ResponseEnvelope:
        try:
            if isinstance(request.payload, GrandidieriteRequest):
                tool_req = dict(request.payload.tool_request or {})
                template_id = request.payload.template_id
            else:
                data = request.payload.model_dump() if hasattr(request.payload, "model_dump") else {}
                tool_req = dict(data.get("tool_request") or {})
                template_id = data.get("template_id", "basic_python_tool")
                # allow top-level action merge
                if "action" in data and "action" not in tool_req:
                    tool_req["action"] = data["action"]

            action = str(tool_req.get("action") or "generate")

            if action == "list":
                catalog = list_tools(True)
                return ResponseEnvelope(
                    task_id=request.task_id,
                    source_gem="grandidierite",
                    payload=GrandidieriteResponse(
                        generated_code=json.dumps(catalog),
                        template_used="list",
                        validation_status="passed",
                    ),
                )

            if action == "run":
                name = str(tool_req.get("name") or "")
                payload = tool_req.get("payload") or {}
                result = run_tool(name, payload)
                return ResponseEnvelope(
                    task_id=request.task_id,
                    source_gem="grandidierite",
                    payload=GrandidieriteResponse(
                        generated_code=json.dumps(result)[:4000],
                        template_used="run",
                        validation_status="passed" if result.get("ok") else "failed",
                    ),
                )

            if action in {"fabricate", "auto", "build"}:
                fab = fabricate(tool_req)
                status = fab.get("validation_status") or "pending"
                # map to schema literals
                if status == "promoted":
                    v = "passed"
                elif status == "failed":
                    v = "failed"
                else:
                    v = "pending"
                return ResponseEnvelope(
                    task_id=request.task_id,
                    source_gem="grandidierite",
                    payload=GrandidieriteResponse(
                        generated_code=json.dumps(fab)[:8000],
                        template_used="fabricate",
                        validation_status=v,
                    ),
                )

            # default: scaffold-only generate into quarantine
            name = _sanitize_name(str(tool_req.get("name", "new_tool")))
            args = tool_req.get("args", "")
            docstring = tool_req.get("docstring", "Auto-generated tool")
            template = self.TEMPLATES.get(template_id, self.TEMPLATES["basic_python_tool"])
            code = template.format(name=name, args=args, docstring=docstring)
            ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
            out = self.quarantine_dir / f"{name}_{ts}.py"
            out.write_text(code, encoding="utf-8")

            return ResponseEnvelope(
                task_id=request.task_id,
                source_gem="grandidierite",
                payload=GrandidieriteResponse(
                    generated_code=code,
                    template_used=template_id,
                    validation_status="pending",
                ),
            )
        except Exception as e:
            return ResponseEnvelope(
                task_id=request.task_id,
                source_gem="grandidierite",
                error=GemError(type=GemErrorType.RUNTIME, message=str(e), recoverable=True),
            )
